services:
  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: merch
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: "8080"
      MYSQL_HOST: db
      MYSQL_PORT: "3306"
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: merch
      STATIC_DIR: /app/web/dist
      MIGRATIONS_PATH: /app/db/migrations
    ports:
      - "${APP_PORT:-8080}:8080"
    volumes:
      - ./db/migrations:/app/db/migrations:ro

volumes:
  db_data:
